### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by vil02** [ujjwall-R/Dree#81]
Why not to add some simple CI? A very simple workflow could look like this:
```yml
---
name: build

'on':
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and run
        run: |
          mkdir -p compile
          $(pwd)/dree.sh 2
...
```

Please note that it only builds and runs the program. It does not perform any verification of the output.
